### ISSUE TITLE
Keybind

### ISSUE THREAD

**Issue by neazen** [ekknod/G37OBS#1]
Can we get more information about the keybinds ?

and possible to add bhop ?

**Comment by ekknod** [comment]
source sdk keybinds:
https://www.onlinegdb.com/fork/HJWsQLtvH
scroll down to main, replace MOUSE_5 with your key and run.

Thanks for the idea, i will add bhop later.

**Comment by neazen** [comment]
kk thanks, btw do you have any idea if it's possible to make this work on faceit or even eac ?
