### ISSUE TITLE
Not working please help

### ISSUE THREAD

**Issue by Formula226** [ekknod/G37OBS#19]
After todays update ur hack is not working its not working

**Comment by kiddico** [comment]
lol, it was an update specifically made to combat this kind of thing.

**Comment by rakion99** [comment]
just wait till obs gets whitelisted or make your own bypass or move obs to windows folder or use https://github.com/danielkrupinski/OneByteLdr or use better cheat ¯\_(ツ)_/¯

**Comment by kiddico** [comment]
Wait... how would moving it to the windows folder help? Just curious.
