### ISSUE TITLE
Esportal? Faceit? Gamersclub?

### ISSUE THREAD

**Issue by jwao** [ekknod/G37OBS#2]
It is possible to use on leagues?

**Comment by ekknod** [comment]
I don't know

**Comment by 0xE232FE** [comment]
For leagues with AntiCheat other than VAC you get busted!

**Comment by jwao** [comment]
> For leagues with AntiCheat other than VAC you get busted! It doesn't matter what you use. You have to manipulate the Hooks of the AntiCheat. For your Information, the most League AntiCheat run Cheat from on its own so they have full Control of the CSGO Process. They Hook the csgo Process like Cheats do and look standard cheat behaviour. Additionally they send any found injected dll to Analysis. So becareful using Cheats on AntiCheat other than VAC, the capture your private dll and make it detected.

But in this case maybe no because OBS is a whitelisted program? 
And if is the case why anticheat don't makes us to get a VAC ban?
