### ISSUE TITLE
Sadly OBS can't inject into CSGO anymore :(

### ISSUE THREAD

**Issue by ArcaneGit** [ekknod/G37OBS#20]
Does anyone know a way to solve this? Is there a tool that patches the game and allows OBS to inject into CSGO?

**Comment by ksoju** [comment]
This was caused when valve updated csgo with trusted mode that prevents third party software from obtaining a handle to the game unless they are signed. Although OBS is signed according to the developers, the game still blocks it from running unless you switch to windows mode for screen capturing. So not very ideal if you're a streamer. Some people have had success getting it to work by installing OBS to c:\windows\ directory and re-enabling game mode. There are other bypasses out there but I have not personally tested them to know if they work or not. In any case, make sure you're using the correct OBS version or G37OBS plugin will fail.
