### ISSUE TITLE
It doesn't seem to be applicable to the newly updated version

### ISSUE THREAD

**Issue by KirsebaerQAQ** [ekknod/G37OBS#22]
csgo has updated a more changed version.need to update the offset?

**Comment by carterjwasd** [comment]
ye, it update is shit how and others

**Comment by KirsebaerQAQ** [comment]
i really hope ekknod can update this. i dont know anything about netvar in it. Its different from anything Ive seen.

**Comment by MOURYAS2001** [comment]
yaa i guess it take ekknod  1 week or maybe 3 days to fix
