### ISSUE TITLE
Any extra security measures ?

### ISSUE THREAD

**Issue by dom0ng** [ekknod/G37OBS#4]
Want to know what detection vector here (for VAC only)? 
Any extra security measures to make it less detectable since it's still RPM/WPM like any externals ?

Good job here, release are pretty insane :)

**Comment by ekknod** [comment]
I will tell when this get detected, as long this project lives i let vac to figure it out :)
I know there is detection vectors, and also this is public.
If i would be vac, i could dectect this.
